### ISSUE TITLE
/assignments works when there are less than 25 assignments

### ISSUE THREAD

**Issue by wma5** [UWSocialComputing/get-it-done-code#4]
The embed message for /assignments uses add_field for each assignment.
add_field has a limit of 25 fields, so might be an issue??

**Comment by kristynhan** [comment]
Resolved in [this commit](https://github.com/UWSocialComputing/get-it-done-code/commit/9edc85eec5d314a5a55b6901d450c3b0f4982992) - assignments are now sent as individual messages with their details in embeds. to solve the issue of spam, they are sent as silent messages in #assignments channel
